# Generated by Django 3.2.3 on 2021-05-15 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalClass',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('fitnessGoal', models.CharField(blank=True, max_length=200, null=True)),
                ('musculeTrained', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workoutNumber', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=2400))),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('date', models.DateTimeField()),
                ('room', models.CharField(blank=True, max_length=200, null=True)),
                ('groupClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.groupclass')),
                ('personalClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.personalclass')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subscribtionFee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('monthlyFee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hasPersonalTrainingFee', models.BooleanField(default=False)),
                ('personalTrainingFee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('totalFee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('beginingDate', models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupclass',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.instructor'),
        ),
    ]
