# Generated by Django 3.2.3 on 2021-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
