# Generated by Django 3.2.3 on 2021-05-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210515_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='image',
        ),
    ]
